#!/usr/bin/env python3
"""Generate a MAIN-BODY vector TikZ compilation figure (subject/results gallery, or corpus collage)
from a panels TSV. Encodes the fixed house style so every survey's galleries look right by default:

  * dark title bar + coloured band headers (grid mode);
  * full-resolution photo tiles, each wrapped in a per-tile \\href hyperlink;
  * the paper/system name printed on the PAGE background in the document link colour
    (ACMDarkBlue for acmart) -- NO dark strip behind the name;
  * the verified figure number in muted grey below the name;
  * a light tile border so tiles separate on white; centred partial rows;
  * \\begin{figure*}[tp] + \\resizebox{\\textwidth}{!}{...} so it lands in the MAIN BODY near its
    \\ref, and is vector (labels crisp at any zoom) with photos embedded at full resolution.

This is the reusable builder behind Figs "subject gallery / results gallery / corpus-at-a-glance"
of the reference survey. See /survey-audit auditor 6 and
.claude/memory/scraped_asset_subject_audit.md for the rules it enforces in code.

Panels TSV (tab-separated, header row `group  tile  name  url  fig`):
  group = band label (grid mode; ignored in collage mode)
  tile  = path to the source image (use --tiles-out to have this tool centre-crop full-res)
  name  = tex-safe paper/system short name        url = https://arxiv.org/abs/<id>
  fig   = verified figure label, e.g. "Fig. 4 p.7"  (leave blank only if UNVERIFIABLE -> drop it)

Usage:
  python3 gen_compilation_figure.py panels.tsv out.tex \\
     --title "Subjects across the surveyed systems" --label fig:subject_gallery \\
     [--mode grid|collage] [--cols 7] [--linkcolor ACMDarkBlue] \\
     [--tiles-out figures/img/gallery_tiles] \\
     [--card "302 systems surveyed;6 branches;2016-2026"]   # collage stats card lines
"""
import os, sys, math, argparse

ACCENTS = ["0B6E4F", "8A5A00", "243B6B", "7A2438", "1F6F8B", "5B3A8A", "555F6B"]

def read_panels(path):
    rows = []
    with open(path) as f:
        header = f.readline().rstrip("\n").split("\t")
        idx = {c: i for i, c in enumerate(header)}
        for line in f:
            if not line.strip(): continue
            p = line.rstrip("\n").split("\t")
            rows.append({k: p[idx[k]] if idx.get(k, 99) < len(p) else "" for k in
                         ("group", "tile", "name", "url", "fig")})
    return rows

def crop(tile, aspect, out):
    from PIL import Image
    Image.MAX_IMAGE_PIXELS = None
    im = Image.open(tile).convert("RGB"); iw, ih = im.size
    if iw/ih > aspect:
        nw = int(round(ih*aspect)); off = (iw-nw)//2; im = im.crop((off, 0, off+nw, ih))
    else:
        nh = int(round(iw/aspect)); off = (ih-nh)//2; im = im.crop((0, off, iw, off+nh))
    im.save(out, quality=92); return out

def prep_tiles(rows, aspect, tiles_out):
    if not tiles_out: return {r["tile"]: r["tile"] for r in rows}
    os.makedirs(tiles_out, exist_ok=True)
    m = {}
    for i, r in enumerate(rows):
        dst = os.path.join(tiles_out, f"tile_{i}.jpg")
        m[r["tile"]] = crop(r["tile"], aspect, dst)
    return m

def grid_tex(rows, title, label, subtitle, cols, link, tilemap):
    W = 13.8; gap = 0.07; tw = (W-(cols+1)*gap)/cols; th = tw*0.72; lh = 0.42; bh = 0.5; titleh = 0.58
    groups, order = {}, []
    for r in rows:
        groups.setdefault(r["group"], []).append(r)
        if r["group"] not in order: order.append(r["group"])
    acc = {g: ACCENTS[i % len(ACCENTS)] for i, g in enumerate(order)}
    L = ["% AUTO-GENERATED by tools/gen_compilation_figure.py -- vector TikZ, main-body, hyperlinked.",
         "\\begin{figure*}[tp]", "\\centering", "\\resizebox{\\textwidth}{!}{%",
         "\\begin{tikzpicture}[x=1cm,y=1cm]"]
    for g in order:
        L.append(f"\\definecolor{{c{acc[g]}}}{{HTML}}{{{acc[g]}}}")
    L.append(f"\\fill[black!88] (0,0) rectangle ({W:.3f},{-titleh:.3f});")
    L.append(f"\\node[anchor=west,text=white,font=\\small\\bfseries,inner sep=0] at (0.14,{-titleh/2:.3f}) {{{title}}};")
    if subtitle:
        L.append(f"\\node[anchor=east,text=white!60,font=\\scriptsize,inner sep=0] at ({W-0.14:.3f},{-titleh/2:.3f}) {{{subtitle}}};")
    y = titleh
    for g in order:
        ids = groups[g]
        L.append(f"\\fill[c{acc[g]}] (0,{-y:.3f}) rectangle ({W:.3f},{-(y+bh):.3f});")
        L.append(f"\\node[anchor=west,text=white,font=\\footnotesize\\bfseries,inner sep=0] at (0.14,{-(y+bh/2):.3f}) {{{g}}};")
        y += bh + gap
        nrows = math.ceil(len(ids)/cols)
        for j, r in enumerate(ids):
            rr, cc = divmod(j, cols)
            ncr = min(cols, len(ids)-rr*cols); roff = (cols-ncr)*(tw+gap)/2
            x = gap + roff + cc*(tw+gap); ty = y + rr*(th+lh+gap)
            u, im = r["url"], tilemap[r["tile"]]
            L.append(f"\\node[anchor=north west,inner sep=0] at ({x:.3f},{-ty:.3f}) {{\\href{{{u}}}{{\\includegraphics[width={tw:.3f}cm]{{{im}}}}}}};")
            L.append(f"\\draw[black!35,line width=0.35pt] ({x:.3f},{-ty:.3f}) rectangle ({x+tw:.3f},{-(ty+th):.3f});")
            L.append(f"\\node[anchor=north west,text={link},font=\\tiny\\bfseries,inner sep=0] at ({x+0.03:.3f},{-(ty+th+0.03):.3f}) {{\\href{{{u}}}{{{r['name']}}}}};")
            if r["fig"]:
                L.append(f"\\node[anchor=north west,text=black!60,font=\\tiny,inner sep=0] at ({x+0.03:.3f},{-(ty+th+0.235):.3f}) {{\\href{{{u}}}{{{r['fig']}}}}};")
        y += nrows*(th+lh+gap)
    L += ["\\end{tikzpicture}}", caption(title, label), descr(title), f"\\label{{{label}}}", "\\end{figure*}"]
    return "\n".join(L) + "\n", tw/th

def collage_tex(rows, title, label, subtitle, cols, link, tilemap, card):
    W = 13.8; gap = 0.05; tw = (W-(cols+1)*gap)/cols; th = tw*0.78; lh = 0.28; titleh = 0.58
    c0, c1, r0, r1 = 2, cols-3, 1, 3            # central card block
    cells = [(c, r) for r in range(5) for c in range(cols) if not (c0 <= c <= c1 and r0 <= r <= r1)]
    L = ["% AUTO-GENERATED by tools/gen_compilation_figure.py -- collage w/ central stats card.",
         "\\begin{figure*}[tp]", "\\centering", "\\resizebox{\\textwidth}{!}{%",
         "\\begin{tikzpicture}[x=1cm,y=1cm]",
         f"\\fill[black!88] (0,0) rectangle ({W:.3f},{-titleh:.3f});",
         f"\\node[anchor=west,text=white,font=\\small\\bfseries,inner sep=0] at (0.14,{-titleh/2:.3f}) {{{title}}};"]
    if subtitle:
        L.append(f"\\node[anchor=east,text=white!60,font=\\scriptsize,inner sep=0] at ({W-0.14:.3f},{-titleh/2:.3f}) {{{subtitle}}};")
    def cellxy(c, r): return gap + c*(tw+gap), titleh + gap + r*(th+lh+gap)
    for k, r in enumerate(rows):
        if k >= len(cells): break
        c, rw = cells[k]; x, y = cellxy(c, rw); u, im = r["url"], tilemap[r["tile"]]
        L.append(f"\\node[anchor=north west,inner sep=0] at ({x:.3f},{-y:.3f}) {{\\href{{{u}}}{{\\includegraphics[width={tw:.3f}cm]{{{im}}}}}}};")
        L.append(f"\\draw[black!35,line width=0.35pt] ({x:.3f},{-y:.3f}) rectangle ({x+tw:.3f},{-(y+th):.3f});")
        L.append(f"\\node[anchor=west,text={link},font=\\tiny,inner sep=0] at ({x+0.03:.3f},{-(y+th+lh/2):.3f}) {{\\href{{{u}}}{{{r['name']}}}}};")
    xl, yt = cellxy(c0, r0); xr, _ = cellxy(c1, 0); xr += tw
    _, yb = cellxy(0, r1); yb += th + lh
    L.append(f"\\fill[white] ({xl:.3f},{-yt:.3f}) rectangle ({xr:.3f},{-yb:.3f});")
    L.append(f"\\draw[black!70,line width=0.6pt] ({xl:.3f},{-yt:.3f}) rectangle ({xr:.3f},{-yb:.3f});")
    lines = (card.split(";") if card else [])
    if lines:
        cx = (xl+xr)/2; yc = yt+0.3; step = (yb-yt-0.5)/max(1, len(lines))
        for i, t in enumerate(lines):
            fnt = "\\footnotesize\\bfseries" if i == 0 else "\\scriptsize"
            L.append(f"\\node[text=black,font={fnt},inner sep=0] at ({cx:.3f},{-yc:.3f}) {{{t}}};"); yc += step
    L += ["\\end{tikzpicture}}", caption(title, label), descr(title), f"\\label{{{label}}}", "\\end{figure*}"]
    return "\n".join(L) + "\n", tw/th

def caption(title, label):
    return ("\\caption{\\textbf{" + title + ".} Each panel is cropped from a figure of the cited paper "
            "and its on-figure label is a clickable hyperlink to that paper; the exact paper, figure "
            "number and page for every panel are listed in Table~\\ref{tab:panel_provenance}. The figure "
            "is a vector graphic with photographs embedded at full resolution, so it may be zoomed "
            "without pixelation. Images \\textcopyright\\ their respective authors, reproduced for "
            "scholarly review.}")

def descr(title):
    return ("\\Description{A labelled grid of images, each a hyperlink annotated with its system name "
            "and source figure number.}")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("panels_tsv"); ap.add_argument("out_tex")
    ap.add_argument("--title", required=True); ap.add_argument("--label", required=True)
    ap.add_argument("--subtitle", default="vector, zoomable, per-panel source links")
    ap.add_argument("--mode", choices=["grid", "collage"], default="grid")
    ap.add_argument("--cols", type=int, default=0)
    ap.add_argument("--linkcolor", default="ACMDarkBlue")
    ap.add_argument("--tiles-out", default="")
    ap.add_argument("--card", default="")
    a = ap.parse_args()
    rows = read_panels(a.panels_tsv)
    rows = [r for r in rows if r["tile"] and (a.mode == "collage" or r["fig"])]  # drop UNVERIFIABLE in grid
    cols = a.cols or (7 if a.mode == "grid" else 8)
    aspect = 1.0/0.72 if a.mode == "grid" else 1.0/0.78
    tilemap = prep_tiles(rows, aspect, a.tiles_out)
    if a.mode == "grid":
        tex, _ = grid_tex(rows, a.title, a.label, a.subtitle, cols, a.linkcolor, tilemap)
    else:
        tex, _ = collage_tex(rows, a.title, a.label, a.subtitle, cols, a.linkcolor, tilemap, a.card)
    open(a.out_tex, "w").write(tex)
    print(f"wrote {a.out_tex} ({len(rows)} panels, {a.mode} mode)")
    print("NOTE: acmart defines ACMDarkBlue; for another class pass --linkcolor <name> and define it.")

if __name__ == "__main__":
    main()
